# Generated by Django 5.2.14 on 2026-05-19 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_remove_opcion_es_ok'),
        ('respuestas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='opcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuestas.opcion'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
