# Generated by Django 5.2.14 on 2026-05-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_remove_opcion_es_ok'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='obligatoriedad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tipo_pregunta',
            field=models.CharField(choices=[('texto', 'texto libre'), ('multiple', 'Opcion multiple')], default='texto', max_length=20),
        ),
    ]
