# Generated by Django 5.2.14 on 2026-05-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0003_pregunta_obligatoriedad_pregunta_tipo_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='borrador', max_length=20),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
    ]
